version: "3.8"

services: 
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - 3001:3001
    volumes: 
      - .:/app
      - '/app/node_modules'
    depends_on: 
      - mysql_server
  
  mysql_server:
    image: mysql:8.0
    environment: 
      - MYSQL_DATABASE=minecraft
      - MYSQL_USER=cmpt354
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./docker/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/init:/docker-entrypoint-initdb.d

    